### ISSUE TITLE
MethodNotAllowedHttpException

### ISSUE THREAD

**Issue by Bagmaz** [iMohammadd/sep-pay#2]
سلام، ببخشید فارسی تایپ میکنم.
وقتی درخواست از سرور برمیگرده من این ارور رو میگیرم و فکر می کنم برای 
csrf token
باشه
نمیدونم چه کاری باید انجام بدم

**Comment by Bagmaz** [comment]
ممنون از این که بعضی از ایرانی های عزیز به هیچ عنوان پاسخگو نیستند.

مشکل من خیلی ساده بود و بی دقتی

در مسیر
app > Http > Middleware > VerifyCsrfToken.php

```
<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/redirect',
    ];
}
```

مسیر بازگشت رو باید اینجا اضافه کرد تا خطای سی اس آر اف نگیره

**Comment by iMohammadd** [comment]
عذر میخوام
ایشوتون رو ندیدم
@Bagmaz
